# Generated by Django 4.1 on 2022-09-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency_default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=255)),
                ('FormalName', models.CharField(max_length=255)),
                ('ISOCurrency', models.CharField(max_length=30, null=True)),
                ('DecimalPlace', models.IntegerField()),
                ('showAmount', models.CharField(max_length=20)),
                ('suffixSymbol', models.CharField(max_length=20)),
                ('AddSpace', models.CharField(max_length=20)),
                ('wordRep', models.CharField(max_length=255, null=True)),
                ('DecimalWords', models.IntegerField()),
            ],
        ),
    ]
