# Generated by Django 4.1 on 2022-09-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0002_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stddate', models.CharField(blank=True, max_length=255, null=True)),
                ('stdrate', models.CharField(default='null', max_length=255)),
                ('selldate', models.CharField(blank=True, max_length=255, null=True)),
                ('selvorate', models.CharField(default='null', max_length=255)),
                ('sellrate', models.CharField(default='null', max_length=255)),
                ('buydate', models.CharField(blank=True, max_length=255, null=True)),
                ('buyvorate', models.CharField(default='null', max_length=255)),
                ('buyrate', models.CharField(default='null', max_length=255)),
                ('currency_default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyAPp2.currency_default')),
            ],
        ),
    ]
