# Generated by Django 4.1 on 2022-09-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0003_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_default',
        ),
        migrations.AddField(
            model_name='currency',
            name='AddSpace',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='DecimalPlace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='DecimalWords',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='FormalName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='ISOCurrency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='Symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='showAmount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='suffixSymbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='wordRep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='buyrate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='buyvorate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sellrate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='selvorate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='stdrate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
