# Generated by Django 4.1 on 2022-09-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0006_p_cost_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('under_name', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_details', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
