# Generated by Django 4.1 on 2022-09-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0008_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='units',
            name='decimal',
        ),
        migrations.RemoveField(
            model_name='units',
            name='first_unit',
        ),
        migrations.RemoveField(
            model_name='units',
            name='formal_name',
        ),
        migrations.RemoveField(
            model_name='units',
            name='second_unit',
        ),
        migrations.RemoveField(
            model_name='units',
            name='uqc',
        ),
    ]
