# Generated by Django 4.1 on 2022-09-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0009_remove_units_conversion_remove_units_decimal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple_Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.CharField(blank=True, max_length=50, null=True)),
                ('uqc', models.CharField(blank=True, max_length=50, null=True)),
                ('decimal', models.IntegerField(blank=True, null=True)),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TallyAPp2.units')),
            ],
        ),
        migrations.CreateModel(
            name='Compound_Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('conversion', models.CharField(blank=True, max_length=50, null=True)),
                ('second_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TallyAPp2.units')),
            ],
        ),
    ]
