# Generated by Django 4.1 on 2022-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0010_simple_units_compound_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound_units',
            name='units',
        ),
        migrations.RemoveField(
            model_name='simple_units',
            name='units',
        ),
        migrations.AddField(
            model_name='compound_units',
            name='type',
            field=models.CharField(blank=True, default='Compound', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simple_units',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simple_units',
            name='type',
            field=models.CharField(blank=True, default='Simple', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
