# Generated by Django 4.1 on 2022-09-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0013_accounts_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='count',
        ),
    ]
