# Generated by Django 4.1 on 2022-09-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0015_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Voucher', models.IntegerField(blank=True, default='', null=True)),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TallyAPp2.accounts')),
            ],
        ),
    ]
