# Generated by Django 4.1 on 2022-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0016_voucher_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='payhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('payhead_type', models.CharField(max_length=100, null=True)),
                ('income_type', models.CharField(max_length=100, null=True)),
                ('under_name', models.CharField(max_length=100, null=True)),
                ('net_salary', models.CharField(max_length=100, null=True)),
                ('pay_slip_name', models.CharField(max_length=100, null=True)),
                ('currency_ledger', models.CharField(max_length=100, null=True)),
                ('calculation_type', models.CharField(max_length=100, null=True)),
                ('round_method', models.CharField(max_length=100, null=True)),
                ('limit', models.CharField(max_length=100, null=True)),
                ('compute', models.CharField(max_length=100, null=True)),
                ('effect_from', models.CharField(max_length=100, null=True)),
                ('grt_than', models.CharField(max_length=100, null=True)),
                ('amt_upto', models.CharField(max_length=100, null=True)),
                ('slab', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
