# Generated by Django 4.1 on 2022-09-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0018_remove_voucher_count_voucher_delete_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compound_Units',
        ),
    ]
