# Generated by Django 4.1 on 2022-09-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0019_delete_compound_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simple_Units',
        ),
    ]
