# Generated by Django 4.1 on 2022-09-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0021_unit_compound_unit_simple_uqcs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currency_default',
            new_name='currencyAlteration',
        ),
    ]
