# Generated by Django 4.1 on 2022-09-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0024_currency_alt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
