# Generated by Django 4.1 on 2022-09-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0026_create_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_Group',
        ),
        migrations.DeleteModel(
            name='P_cost_default',
        ),
    ]
