# Generated by Django 4.1 on 2022-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0027_delete_employee_group_delete_p_cost_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_employeegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('define_salary', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='emp_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=225)),
                ('cat_alias', models.CharField(max_length=225)),
                ('revenue_items', models.CharField(max_length=225)),
                ('non_revenue_items', models.CharField(max_length=225)),
            ],
        ),
    ]
