# Generated by Django 4.1 on 2022-09-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0028_create_employeegroup_emp_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
