# Generated by Django 4.1 on 2022-09-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0031_remove_currency_alt_currencyalteration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='currencyAlteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=255)),
                ('FormalName', models.CharField(max_length=255)),
                ('ISOCurrency', models.CharField(max_length=30, null=True)),
                ('DecimalPlace', models.IntegerField()),
                ('showAmount', models.CharField(max_length=20)),
                ('suffixSymbol', models.CharField(max_length=20)),
                ('AddSpace', models.CharField(max_length=20)),
                ('wordRep', models.CharField(max_length=255, null=True)),
                ('DecimalWords', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='currency_alt',
            name='currencyAlteration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyAPp2.currencyalteration'),
        ),
    ]
