# Generated by Django 4.1 on 2022-09-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0032_currencyalteration_currency_alt_currencyalteration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
