# Generated by Django 4.1 on 2022-09-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyAPp2', '0033_delete_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payhead',
        ),
    ]
