from . import views
from django.urls import path

urlpatterns = [
    path('',views.home,name='home'),
    path('units/',views.units,name='units'),
    path('base/',views.base,name='base'),
    path('currencies/',views.currencies,name='currencies'),
    path('atten_prod/',views.atten_prod,name='atten_prod'),
    path('emp_groups/',views.emp_groups,name='emp_groups'),
    path('employee/',views.employee,name='employee'),
    path('curr_alter/<int:pk>',views.curr_alter,name='curr_alter'),
    path('unit_alter/<int:pk>',views.unit_alter,name='unit_alter'),
    path('curr_alter2/<int:pk>',views.curr_alter2,name='curr_alter2'),
    path('atten_alter/<int:pk>',views.atten_alter,name='atten_alter'),
    path('empg_alter/<int:pk>',views.empg_alter,name='empg_alter'),
    path('empg_details/<int:pk>',views.empg_details,name='empg_details'),
    path('create_pay_head/',views.create_pay_head,name='create_pay_head'),
    path('p_cost/<int:pk>',views.p_cost,name='p_cost'),
    path('emp_alter/<int:pk>',views.emp_alter,name='emp_alter'),
    path('c_unit_alter/<int:pk>',views.c_unit_alter,name='c_unit_alter'),
    path('simple_unit_alter/<int:pk>',views.simple_unit_alter,name='simple_unit_alter'),
    path('compound_unit_alter/<int:pk>',views.compound_unit_alter,name='compound_unit_alter'),
    path('curr_default_alter/<int:pk>',views.curr_default_alter,name='curr_default_alter'),
    path('currency_altern/<int:pk>',views.currency_altern,name='currency_altern'),
    path('attendance_alter/<int:pk>',views.attendance_alter,name='attendance_alter'),
    path('pcost_alter/<int:pk>',views.pcost_alter,name='pcost_alter'),
    path('employee_grp_alter/<int:pk>',views.employee_grp_alter,name='employee_grp_alter'),
    path('employee_alter/<int:pk>',views.employee_alter,name='employee_alter'),
    path('attend_create/',views.attend_create,name='attend_create'),
    path('add_pay_head/',views.add_pay_head,name='add_pay_head'),
]